backend/app_account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app_account import views

app_name = "app_account"

urlpatterns = [
    path("login/", views.LogInView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    # path('signup/', views.signup_view, name='signup'),
    path("api/v1/", include("app_account.api.v1.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/app_blog/urls.py
from django.urls import path, include
from app_blog import views
from django.conf import settings
from django.conf.urls.static import static
from app_blog.feeds import LatestEntriesFeed

app_name = "app_blog"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("blog/", views.blog_view, name="blog"),
    path("blog/category/<str:category>/", views.blog_view, name="blog_category"),
    path("blog/tag/<str:tag>/", views.blog_view, name="blog_tag"),
    path("blog/author/<str:author>/", views.blog_view, name="blog_author"),
    path("blog/<int:pid>/", views.single_post_view, name="single"),
    path("contact/", views.contact_view, name="contact"),
    path("about/", views.about_view, name="about"),
    path("rss/feed/", LatestEntriesFeed()),
    path("blog/api/v1/", include("app_blog.api.v1.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/app_todo/urls.py
from django.urls import path, include
from .views import (
    TaskList,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TestSendEmail,
    TestCache
)

app_name = "app_todo"

urlpatterns = [
    path("tasks/", TaskList.as_view(), name="task_list"),
    path("tasks/create/", TaskCreate.as_view(), name="create_task"),
    path("tasks/update/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path("tasks/delete/<int:pk>/", TaskDelete.as_view(), name="delete_task"),
    path("api/v1/", include("app_todo.api.v1.urls")),

    # test send email using celery
    path("test-send-email/", TestSendEmail.as_view()),

    # test cache
    path("test-cache/", TestCache.as_view()),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from app_blog.sitemaps import BlogSitemap, StaticViewSitemap

sitemaps = {
    "blog": BlogSitemap,
    "static": StaticViewSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_blog.urls")),
    path("todo/", include("app_todo.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("app_account.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    # api documents
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

backend/templates/base/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="description" content="this is a test website to learn django and seo">

    <!-- Facebook -->
    <meta property="og:title" content="home page(django learning)">
    <meta property="og:description" content="this is a test website to learn django and seo">
    <meta property="og:image" content="https://testhostmtp.com/static/images/favicon.jpg">
    <meta property="og:url" content="https://testhostmtp.com">

    <!-- twitter -->
    <meta name="twitter:title" content="Add title here">
    <meta name="twitter:description" content="Add description here">
    <meta name="twitter:url" content="https://testhostmtp.com/static/images/favicon.jpg">
    <meta name="twitter:card" content="summary">


  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/favicon.jpg' %}" >

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">




  <!-- =======================================================
  * Template Name: FlexStart
  * Updated: Jul 27 2023 with Bootstrap v5.3.1
  * Template url: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'app_blog:home' %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="flexstart logo">
        <span>FlexStart</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto {% block home_active %}active{% endblock %}" href="{% url 'app_blog:home' %}">Home</a></li>
          <li><a class="nav-link scrollto {% block about_active %}{% endblock %}" href="{% url 'app_blog:about' %}">About</a></li>
          <li><a class="nav-link scrollto {% block blog_active %}{% endblock %}" href="{% url 'app_blog:blog' %}">Blog</a></li>
          <li><a class="nav-link scrollto {% block contact_active %}{% endblock %}" href="{% url 'app_blog:contact' %}">Contact</a></li>
          <li><a class="nav-link scrollto {% block todo_active %}{% endblock %}" href="{% url 'app_todo:task_list' %}">tasks</a></li>
          {% if request.user.is_authenticated %}
            <li><a class="nav-link scrollto" href="{% url 'app_account:logout' %}">Logout</a></li>
              <li class="nav-link scrollto">{{ request.user.username }}</li>
          {% else %}
            <li><a class="nav-link scrollto" href="{% url 'app_account:login' %}">Login</a></li>
{#            <li><a class="nav-link scrollto" href="{% url 'app_account:signup' %}">Sign Up</a></li>#}
        {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
    <br>
    <br>
    <br>
    <br>
  {% block content %}
  {% endblock %}


  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
                {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="index.html" class="logo d-flex align-items-center">
              <img src="{% static 'assets/img/logo.png' %}" alt="flexstart logo">
              <span>FlexStart</span>
            </a>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>FlexStart</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static "assets/js/popper.min.js" %}"></script>
  <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>


    {% include 'app_blog/_modal-message.html' %}

</body>

</html>