backend/app_account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app_account import views

app_name = "app_account"

urlpatterns = [
    path("login/", views.LogInView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    # path('signup/', views.signup_view, name='signup'),
    path("api/v1/", include("app_account.api.v1.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/app_blog/api/v1/urls.py
# from django.urls import path
from app_blog.api.v1 import views
from rest_framework.routers import DefaultRouter

app_name = "api_v1"

urlpatterns = [
    # path('posts/', views.PostViewSet.as_view({'get': 'list', 'post': 'create'})),
    # path('posts/<int:pk>/', views.PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'patch': 'partial_update'})),
]

router = DefaultRouter()
router.register(r"post", views.PostViewSet, basename="post")
urlpatterns += router.urls

backend/app_blog/urls.py
from django.urls import path, include
from app_blog import views
from django.conf import settings
from django.conf.urls.static import static
from app_blog.feeds import LatestEntriesFeed

app_name = "app_blog"

urlpatterns = [
    path("", views.home_view, name="home"),
    path("blog/", views.blog_view, name="blog"),
    path("blog/category/<str:category>/", views.blog_view, name="blog_category"),
    path("blog/tag/<str:tag>/", views.blog_view, name="blog_tag"),
    path("blog/author/<str:author>/", views.blog_view, name="blog_author"),
    path("blog/<int:pid>/", views.single_post_view, name="single"),
    path("contact/", views.contact_view, name="contact"),
    path("about/", views.about_view, name="about"),
    path("rss/feed/", LatestEntriesFeed()),
    path("blog/api/v1/", include("app_blog.api.v1.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from app_blog.sitemaps import BlogSitemap, StaticViewSitemap

sitemaps = {
    "blog": BlogSitemap,
    "static": StaticViewSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_blog.urls")),
    path("todo/", include("app_todo.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("app_account.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    # api documents
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

backend/app_blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from app_account.models import Profile
from django.utils.timezone import now


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(default=now)
    status = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to="app_blog/posts/images/", null=True, blank=True)
    categories = models.ManyToManyField("Category", db_table="app_blog_post_category")
    tags = TaggableManager(blank=True)

    class Meta:
        db_table = "app_blog_post"

    def __str__(self):
        return str(self.id) + "-" + self.title

    def get_absolute_url(self):
        return reverse("app_blog:single", kwargs={"pid": self.id})

    def get_absolute_api_url(self):
        return reverse("app_blog:api_v1:post-detail", kwargs={"pk": self.id})


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = "app_blog_category"
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "app_blog_contact"
        verbose_name = "contact"
        verbose_name_plural = "contacts"

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    allowed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "app_blog_comment"
        verbose_name = "comment"
        verbose_name_plural = "comments"

    def __str__(self):
        return str(self.id) + "-" + self.subject

backend/app_blog/forms.py
from django import forms
from app_blog.models import Contact, Comment
from captcha.fields import CaptchaField


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = "__all__"


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        fields = ["post", "name", "email", "subject", "message"]

backend/app_blog/api/v1/views.py
# from rest_framework.response import Response
# from django.shortcuts import get_object_or_404
from rest_framework import permissions
from rest_framework import viewsets
from app_blog.models import Post
from app_blog.api.v1.serializers import PostSer
from app_blog.api.v1.permissions import PostModelIsOwnerOrReadOnly
from app_blog.api.v1.paginations import PostPagination
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters


# class PostViewSet(viewsets.ViewSet):
#     permission_classes = [permissions.IsAuthenticatedOrReadOnly]
#     serializer_class = PostSer
#
#     def list(self, request):
#         queryset = Post.objects.filter(status=True)
#         serializer = self.serializer_class(queryset, many=True)
#         return Response(serializer.data)
#
#     def retrieve(self, request, pk=None):
#         post = get_object_or_404(Post, pk=pk, status=True)
#         serializer = self.serializer_class(post)
#         return Response(serializer.data)
#
#     def create(self, request):
#         serializer = self.serializer_class(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)
#
#     def update(self, request, pk=None):
#         post = get_object_or_404(Post, pk=pk, status=True)
#         serializer = self.serializer_class(post, data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)
#
#     def partial_update(self, request, pk=None):
#         post = get_object_or_404(Post, pk=pk, status=True)
#         serializer = self.serializer_class(post, data=request.data, partial=True)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)
#
#     def destroy(self, request, pk=None):
#         post = get_object_or_404(Post, pk=pk, status=True)
#         post.delete()
#         return Response('post deleted')


class PostViewSet(viewsets.ModelViewSet):
    permission_classes = [
        permissions.IsAuthenticatedOrReadOnly,
        PostModelIsOwnerOrReadOnly,
    ]
    serializer_class = PostSer
    queryset = Post.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    ]
    filterset_fields = ["categories", "author", "status"]
    search_fields = ["title"]
    ordering_fields = ["published_date"]
    pagination_class = PostPagination

backend/app_blog/views.py
from django.shortcuts import render, redirect
from app_blog.models import Post, Comment
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from app_blog.forms import ContactForm, CommentForm
from django.contrib import messages


def home_view(request):
    return render(request, "app_blog/index.html")


def blog_view(request, **kwargs):
    posts = Post.objects.filter(published_date__lte=timezone.now(), status=1).order_by(
        "-published_date"
    )

    if s := request.GET.get("search"):
        posts = posts.filter(title__contains=s)
    if a := kwargs.get("author"):
        posts = posts.filter(author__username=a)
    if c := kwargs.get("category"):
        posts = posts.filter(categories__name=c)
    if t := kwargs.get("tag"):
        posts = posts.filter(tags__name__icontains=t)

    posts = Paginator(posts, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = posts.page(page_number)
    except PageNotAnInteger:
        return redirect("app_blog:post_list")
    except EmptyPage:
        return redirect("app_blog:post_list")

    context = {"posts": posts}
    return render(request, "app_blog/blog.html", context)


def single_post_view(request, pid):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Comment Saved.")
        else:
            messages.error(request, form.errors)
        return redirect("app_blog:single", pid=pid)

    form = CommentForm()
    post_id_list = [
        post.id for post in Post.objects.all().filter(status=1).order_by("id")
    ]
    post = Post.objects.get(id=pid)
    comments = Comment.objects.filter(post=post, allowed=True)
    try:
        next_post = Post.objects.get(id=post_id_list[post_id_list.index(pid) + 1])
    except:
        next_post = None
    try:
        if post_id_list.index(pid) - 1 == -1:
            raise ValueError
        previous_post = Post.objects.get(id=post_id_list[post_id_list.index(pid) - 1])
    except:
        previous_post = None
    try:
        post.views += 1
        post.save()
    except:
        return redirect("app_blog:home")
    context = {
        "form": form,
        "post": post,
        "previous_post": previous_post,
        "next_post": next_post,
        "comments": comments,
    }
    return render(request, "app_blog/blog-single.html", context)


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "message saved.")
            return redirect("app_blog:home")
        else:
            messages.error(request, form.errors)
            return redirect("app_blog:contact")

    form = ContactForm()
    context = {"form": form}
    return render(request, "app_blog/contact.html", context)


def about_view(request):
    return render(request, "app_blog/about.html")

backend/templates/app_blog/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="description" content="this is a test website to learn django and seo">

    <!-- Facebook -->
    <meta property="og:title" content="home page(django learning)">
    <meta property="og:description" content="this is a test website to learn django and seo">
    <meta property="og:image" content="https://testhostmtp.com/static/images/favicon.jpg">
    <meta property="og:url" content="https://testhostmtp.com">

    <!-- twitter -->
    <meta name="twitter:title" content="Add title here">
    <meta name="twitter:description" content="Add description here">
    <meta name="twitter:url" content="https://testhostmtp.com/static/images/favicon.jpg">
    <meta name="twitter:card" content="summary">


  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/favicon.jpg' %}" >

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">




  <!-- =======================================================
  * Template Name: FlexStart
  * Updated: Jul 27 2023 with Bootstrap v5.3.1
  * Template url: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'app_blog:home' %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="flexstart logo">
        <span>FlexStart</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto {% block home_active %}active{% endblock %}" href="{% url 'app_blog:home' %}">Home</a></li>
          <li><a class="nav-link scrollto {% block about_active %}{% endblock %}" href="{% url 'app_blog:about' %}">About</a></li>
          <li><a class="nav-link scrollto {% block blog_active %}{% endblock %}" href="{% url 'app_blog:blog' %}">Blog</a></li>
          <li><a class="nav-link scrollto {% block contact_active %}{% endblock %}" href="{% url 'app_blog:contact' %}">Contact</a></li>
          {% if request.user.is_authenticated %}
            <li><a class="nav-link scrollto" href="{% url 'app_account:logout' %}">Logout</a></li>
              <li class="nav-link scrollto">{{ request.user.username }}</li>
          {% else %}
            <li><a class="nav-link scrollto" href="{% url 'app_account:login' %}">Login</a></li>
            <li><a class="nav-link scrollto" href="{% url 'app_account:signup' %}">Sign Up</a></li>
        {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
    <br>
    <br>
    <br>
    <br>
  {% block content %}
  {% endblock %}






  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
                {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="index.html" class="logo d-flex align-items-center">
              <img src="{% static 'assets/img/logo.png' %}" alt="flexstart logo">
              <span>FlexStart</span>
            </a>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>FlexStart</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static "assets/js/popper.min.js" %}"></script>
  <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>


    {% include 'app_blog/_modal-message.html' %}

</body>

</html>

backend/templates/app_blog/_blog-author-section.html
<h3 class="sidebar-title">Authors</h3>
<div class="sidebar-item categories">
    <ul>

        {% for author in authors %}
            <li><a href="{% url 'app_blog:blog_author' author  %}">{{ author }}</a></li>
        {% endfor %}
    </ul>
</div><!-- End sidebar categories-->

backend/templates/app_blog/blog-single.html
{% extends 'base/_base.html' %}
{% load static %}
{% load humanize %}
{% load tags %}


{% block title %}
    {{ post.title }}
{% endblock %}

{% block home_active %}
{% endblock %}

{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{% url 'app_blog:home' %}">Home</a></li>
          <li><a href="{% url 'app_blog:blog' %}">Blog</a></li>
          <li>Blog Single</li>
        </ol>
        <h2>Blog Single</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="blog-single.html">{{ post.title }}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ post.author }}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ post.published_date|naturalday }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#comments">{% counting_post_comments post.id %} comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  Similique neque nam consequuntur ad non maxime aliquam quas. Quibusdam animi praesentium. Aliquam et laboriosam eius aut nostrum quidem aliquid dicta.
                  Et eveniet enim. Qui velit est ea dolorem doloremque deleniti aperiam unde soluta. Est cum et quod quos aut ut et sit sunt. Voluptate porro consequatur assumenda perferendis dolore.
                </p>

              </div>

              <div class="entry-footer">
                <i class="bi bi-tags"></i>
                <ul class="tags">
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'app_blog:blog_tag' tag.name %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
              </div>
            <div class="entry-footer">
                views: {{ post.views }}
              </div>

            </article><!-- End blog entry -->

            <div class="blog-author d-flex align-items-center">
              <img src="{% static 'assets/img/blog/blog-author.jpg' %}" class="rounded-circle float-left" alt="blog-author">
              <div>
                <h4>Jane Smith</h4>
                <div class="social-links">
                  <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                </div>
                <p>
                  Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                </p>
              </div>
            </div><!-- End blog author bio -->

              <!-- comments -->
            <div class="blog-comments" id="comments">

              <h4 class="comments-count">{% counting_post_comments post.id %} Comments</h4>

            {% if comments %}
                {% for comment in comments %}
              <div class="comment">
                <div class="d-flex">
                  <div>
                    <h4>{{ comment.name }}<a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a></h4>
                    <h4>{{ comment.subject }}</h4>
                    <time datetime="2020-01-01">{{ comment.created_date|naturalday }}</time>
                    <p>{{ comment.message }}</p>
                  </div>
                </div>
              </div><!-- End comment #1 -->
                {% endfor %}
            {% endif %}

              <div class="reply-form">
                <h4>Leave a Reply</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                <form action="" method="post">
                    {% csrf_token %}

                    <input name="post" type="hidden"  value="{{ post.id }}">
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*">
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="text" class="form-control" placeholder="Your Email*">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <input name="subject" type="text" class="form-control" placeholder="subject">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <textarea name="message" class="form-control" placeholder="Your Comment*"></textarea>
                    </div>
                  </div>
                    <div class="pb-3">
                            {{ form.captcha }}
                    </div>
                  <button type="submit" class="btn btn-primary">Post Comment</button>

                </form>

              </div>

            </div>
              <!-- End blog comments -->

          </div><!-- End blog entries list -->

            <!-- sidebar -->
          <div class="col-lg-4">

            <div class="sidebar">


                <!-- categories -->
                {% category_section %}

                <!-- latest posts -->
                {% latest_posts %}

                <!-- tags -->
                {% tag_section %}


            </div><!-- End sidebar -->

          </div>
            <!-- End blog sidebar -->


        <div class="navigation-area" style="text-align: center; border: 1px solid black; border-radius: 1rem">
                        {% if previous_post %}
                        <!-- previous post -->
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-center align-items-center">

                                <div class="arrow">
                                    <a href="{% url 'app_blog:single' previous_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
                                </div>
                                <div class="detials">
                                    <p>Prev Post</p>
                                    <a href="{% url 'app_blog:single' previous_post.id %}"><h4>{{ previous_post.title }}</h4></a>
                                </div>
                            </div>
                        {% endif %}

                        {% if next_post %}
                        <!-- next post -->
                            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-center align-items-center">
                                <div class="detials">
                                    <p>Next Post</p>
                                    <a href="{% url 'app_blog:single' next_post.id %}"><h4>{{ next_post.title }}</h4></a>
                                </div>
                                <div class="arrow">
                                    <a href="{% url 'app_blog:single' next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
                                </div>

                            </div>
                        </div>
                        {% endif %}
                    </div>

        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->
{% endblock %}