backend/app_todo/api/v1/urls.py
from django.urls import path
from app_todo.api.v1 import views

app_name = "api_v1"

urlpatterns = [
    path("tasks/", views.TaskListView.as_view(), name="task_list"),
    path("tasks/<int:pk>/", views.TaskDetailAPIView.as_view(), name="task_detail"),

    # testing cache
    path("test-cache/", views.TestCacheAPIView.as_view(), name="test-cache"),

    # get weather
    path("weather/", views.GetWeatherAPIView.as_view(), name="weather"),
]

backend/app_todo/urls.py
from django.urls import path, include
from .views import (
    TaskList,
    TaskCreate,
    TaskUpdate,
    TaskDelete,
    TestSendEmail,
    TestCache
)

app_name = "app_todo"

urlpatterns = [
    path("tasks/", TaskList.as_view(), name="task_list"),
    path("tasks/create/", TaskCreate.as_view(), name="create_task"),
    path("tasks/update/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path("tasks/delete/<int:pk>/", TaskDelete.as_view(), name="delete_task"),
    path("api/v1/", include("app_todo.api.v1.urls")),

    # test send email using celery
    path("test-send-email/", TestSendEmail.as_view()),

    # test cache
    path("test-cache/", TestCache.as_view()),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
from app_blog.sitemaps import BlogSitemap, StaticViewSitemap

sitemaps = {
    "blog": BlogSitemap,
    "static": StaticViewSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_blog.urls")),
    path("todo/", include("app_todo.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("app_account.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    # api documents
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

backend/app_todo/models.py
from django.db import models
from django.urls import reverse
from app_account.models import Profile


class Task(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id) + "-" + str(self.title)

    def get_absolute_api_url(self):
        return reverse("app_todo:api_v1:task_detail", kwargs={"pk": self.id})

    class Meta:
        db_table = "app_todo_task"

backend/app_todo/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("title", "status")

backend/app_todo/api/v1/views.py
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
import requests
from app_todo.models import Task
from app_todo.api.v1.serializers import TaskSer
from app_todo.api.v1.paginations import TaskPagination
from app_todo.utils import get_random_number


class TaskListView(generics.ListCreateAPIView):
    serializer_class = TaskSer
    permission_classes = [IsAuthenticated]
    pagination_class = TaskPagination
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["status"]

    def get_queryset(self):
        return Task.objects.filter(user__user=self.request.user)


class TaskDetailAPIView(APIView):
    serializer_class = TaskSer
    permission_classes = [IsAuthenticated]

    def get(self, request, pk, format=None):
        task = get_object_or_404(Task, pk=pk, user__user=request.user)
        serializer = self.serializer_class(task, context={"request": request})
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        task = get_object_or_404(Task, pk=pk, user__user=request.user)
        serializer = self.serializer_class(task, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"detail": "task updated!"}, status=status.HTTP_200_OK)

    def delete(self, request, pk, format=None):
        task = get_object_or_404(Task, pk=pk, user__user=request.user)
        try:
            task.delete()
            return Response(
                {"detail": "task deleted!"}, status=status.HTTP_204_NO_CONTENT
            )
        except:
            return Response(
                {"detail": "deleting failed!"}, status=status.HTTP_400_BAD_REQUEST
            )


class TestCacheAPIView(APIView):
    """
    this view is for testing cache performance.
    """

    @method_decorator(cache_page(60 * 60 * 2))
    def get(self, request, *args, **kwargs):
        n = get_random_number()
        return Response({'number': n})


class GetWeatherAPIView(APIView):

    url = "https://api.openweathermap.org/data/2.5/weather?lat=35.72&lon=51.33&appid={}"
    api_key = ""  # use correct api key

    @method_decorator(cache_page(60 * 20))
    def get(self, request, *args, **kwargs):
        r = requests.get(self.url.format(self.api_key))
        return Response(r.json())

backend/app_todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, View
from django.shortcuts import redirect
from django.core.cache import cache
from .forms import TaskForm
from .models import Task
from app_todo.tasks import send_email
from app_todo.utils import get_random_number



class TaskList(LoginRequiredMixin, ListView):
    context_object_name = "tasks"
    template_name = "app_todo/task_list.html"

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user.profile)


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title", "status"]
    success_url = reverse_lazy("app_todo:task_list")

    def form_valid(self, form):
        form.instance.user = self.request.user.profile
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    success_url = reverse_lazy("app_todo:task_list")
    form_class = TaskForm
    template_name = "app_todo/update_task.html"


class TaskDelete(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy("app_todo:task_list")

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.success_url)

    def get_queryset(self):
        return Task.objects.filter(pk=self.kwargs.get("pk"))


class TestSendEmail(View):
    def get(self, request):
        send_email.delay()
        return HttpResponse('<h1>email sending!</h1>')


class TestCache(View):
    """
    this view is for testing cache performance.
    """

    def get(self, request, *args, **kwargs):
        if n := cache.get("random_number"):
            return HttpResponse("<h1>number: {}</h1>".format(n))

        n = get_random_number()
        cache.set("random_number", n)
        return HttpResponse("<h1>number: {}</h1>".format(n))

backend/templates/app_todo/task_list.html
{% extends 'base/_base.html' %}
{% load static %}

{% block title %} task List {% endblock %}
{% block todo_active %}active{% endblock %}
{% block home_active %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" action="{% url 'app_todo:create_task' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.status == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'app_todo:delete_task' task.id %}"><i class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'app_todo:update_task' task.id %}">Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/templates/app_todo/update_task.html
{% extends 'base/_base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block todo_active %}active{% endblock %}
{% block home_active %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'app_todo:task_list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">
                        {{form.as_p}}
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}